# My aliases
alias a='alias'
alias ea='vim ~/.bash_aliases'
alias ga='git add && git commit'
alias l='ls -alFhi --color=auto'
alias la='ls -A'
alias v='vim'
alias c='clear'
alias ch='chmod +x'
alias m='man'
alias r='ranger'
alias s='sudo'
alias sr='source .bashrc'
alias sp='source ~/pythoncode/pythontest/pythontest/bin/activate'
alias t='type'
alias vb='vim ~/.bashrc'
alias vv='vim ~/.vimrc'
